config/routes.rb
Rails.application.routes.draw do
  resources :items

  get 'items/:id/publish' => 'items#publish', as: :publish_item
  get 'items/:id/hide' => 'items#hide', as: :hide_item

  devise_for :users

  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :title, presence: true

  def publish
    update_attributes public: true
  end

  def hide
    update_attributes public: false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :publish, :hide]

  # GET /items
  # GET /items.json
  def index
    @items = current_user.items
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_url, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    @item.publish
    redirect_to items_url, notice: 'Item was successfully published.'
  end

  def hide
    @item.hide
    redirect_to items_url, notice: 'Item was successfully privatized.'
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = current_user.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params[:item][:user_id] = current_user.id
      params.require(:item).permit(:title, :link, :user_id, :image)
      # params.require(:item).permit(:title, :link, :user_id, image: [:tempfile, :original_filename, :content_type, :headers])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @items = Item.where public: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for @item, html: { multipart: true }, class: 'form-horizontal' do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissible" role="alert">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :link %><br />
    <%= f.text_field :link, class: 'form-control' %>
  </div>
  <%= f.file_field :image %>
  <% if @item.image.exists? %>
    <%= link_to image_tag(@item.image.url(:medium)), @item.image.url %>
  <% end %>
  <div class="actions">
    <%= f.submit class: 'btn btn-default btn-primary' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path, class: 'btn btn-small' %>

app/views/items/index.html.erb
<div class="pull-left">
  <h1>My Media items</h1>
</div>
<div class="pull-right">
  <%= link_to 'New Item', new_item_path, class: 'btn btn-primary' %>
</div>
<div class='clearfix'></div>

<table class="table table-bordered table-striped">
  <tbody>
    <% @items.each do |item| %>
      <tr class="row">
        <td class="col-md-1">
          <% unless item.public? %>
            <%= link_to 'Publish', publish_item_path(item), class: 'btn btn-success' %>
          <% else %>
            <%= link_to 'Conceal', hide_item_path(item), class: 'btn btn-warning' %>
          <% end %>
        </td>
        <td class="col-md-9">
          <% unless item.public? %>
            <span class="fa fa-eye-slash" aria-hidden="true"></span>
          <% else %>
            <span class="fa fa-eye" aria-hidden="true"></span>
          <% end %>
          <%= item.title %>
          <% if item.link.present? %>
            <br />
            <span class="fa fa-arrow-right" aria-hidden="true"></span>
            <%= link_to item.link, item.link, target: '_blank' %>
          <% end %>
          <% if item.image.exists? %>
            <br />
            <%= link_to image_tag(item.image.url(:medium)), item.image.url %>
          <% end %>
        </td>
        <td class="col-md-2">
          <%= link_to 'Edit', edit_item_path(item), class: 'btn btn-success' %>
          <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path, class: 'btn btn-small' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mediapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= nav_bar brand: "Shared Media" do %>
      <% menu_group pull: :right do %>
        <% if user_signed_in? %>
          <%= menu_item "My Media", items_path %>
          <%= menu_item "Edit Profile", edit_user_registration_path %>
          <%= menu_item "Log Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= menu_item "Sign up", new_user_registration_path %>
          <%= menu_item "Login", new_user_session_path %>
        <% end %>
      <% end %>
  <% end %>
  <div class="container">
    <%= bootstrap_flash %>
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<table class="table table-bordered table-striped">
  <tbody>
    <% @items.each do |item| %>
      <tr class="row">
        <td class="col-md-12">
          <% if item.link.present? %>
            <%= link_to item.title, item.link, target: '_blank' %>
          <% else %>
            <%= item.title %>
          <% end %>
          <% if item.image.exists? %>
            <br />
            <%= link_to image_tag(item.image.url(:medium)), item.image.url, target: '_blank' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>